configfile: "resources/configs/StickleSnake.yaml" #We need to specify the config file that contains the parameters for the script
#templates = glob_wildcards("data/templates/template_*.png") #This is to get the list of template images in the "data/templates" folder, which will be used for the template matching step in the measure_fish rule. The glob_wildcards function is used to extract the template names from the file names, which will be used to match the templates with the corresponding annotation files.
#image_names = glob_wildcards("data/raw_images/*.jpg") #This is to get the list of raw images in the "data/raw_images" folder, which will be used as input for the read_label and crop_fish rules. The glob_wildcards function is used to extract the image names from the file names, which will be used to match the images with the corresponding log files and cropped images.

#rule all:
#    input:
#        "data/cropped_images" #This is the final output of the pipeline, which is the folder containing the labelled images after processing.
#        "data/raw_images/measurements.csv" #indicatign that the fish have been measured


rule read_label: #Rule to read the label using a trained OCR model and save the output 
    input:
        images_dir="data/raw_images" #input folder path
    output:
        "data/raw_images/label_log.json" #log file (robust in case files are renamed, as the log file will be saved in the same directory as the images)
    container:
        config["container"] #We need to specify the container that contains the trained OCR model and the necessary dependencies to run the script
    log:
        notebook="logs/read_label.log" #log file path
    shell:
        "python3 scripts/read_label.py "
        "--log_file {config[log_file_label]} "
        "--image_dir {input.images_dir} "
        "--flip {config[flip_label]} "
        "--pattern {config[pattern]} "
        "--rename {config[rename]} "
        "--save_ocr_visualization {config[save_ocr_visualization]}"

rule crop_fish: #Rule to read a fish image, crop the fish using the bounding box coordinates obtained from the OCR model and save the cropped image in a new folder. This step is optional and can be skipped if the user only wants to read the labels without cropping the images. 
    input:
        "data/raw_images/label_log.json", #log file generated by the read_label script, meaning that this has run to completion and the labels have been read successfully.
        images_dir="data/raw_images" #input folder path
    output:
        directory("data/cropped_images") #folder of cropped images created by the script (robust in case files are renamed, as the cropped images will be saved in a new folder)
    container:
        config["container"] #We need to specify the container that contains the trained model and the necessary dependencies to run the script
    log:
        notebook="logs/crop_fish.log" #log file path
    shell:
        "python3 scripts/crop_images.py "
        "--path {input.images_dir} "
        "--flip {config[right_side_up]} "
        "--out_dir {output} "
        "--pipeline_config_path {config[crop_config]} "
        "--label_path {config[crop_label_file]} "
        "--checkpoint {config[checkpoint_prefix]} "
        "--save_bbox_coordinates {config[save_bbox_coordinates]} "
        "--display_image_with_bbox {config[display_image_with_bbox]} "
        "--save_image_with_bbox {config[save_image_with_bbox]} "
        "--save_cropped_image {config[save_cropped_image]}"


checkpoint measure_fish: #Rule to extract the pixel/unit distance data from an image, using template matching
    input: 
        "data/raw_images/label_log.json", #log file generated by the read_label script, meaning that this has run to completion and the labels have been read successfully.
        image = "data/raw_images/{image_name}.jpg", #input folder path of cropped images
        template = "data/templates/template_{template_name}.png" #template image file generated by the earliest script, which contains the pixel/unit distance data for the template image. 
    conda: "envs/phenopype.yaml" #We need to specify the conda environment
    log: 
        notebook="logs/measure_fish_{image_name}_{template_name}.log" #log file path
    output:
        annotation = "data/measurements/{image_name}_{template_name}_annotation.json" #folder containing the measurements of each file in "raw images"
    shell:
        "python3 scripts/measure_light.py "
        "--input_image {input.image} "
        "--input_template {input.template} "
        "--input_annotation data/templates/annotation_{wildcards.template_name}.json"

rule specimen_measurements_done:
    input:
        # aggregate all annotation files produced by measure_fish
        lambda wildcards: [
            os.path.join("data/measurements", f)
            for f in os.listdir("data/measurements")
            if f.endswith("_annotation.json")
        ] if os.path.exists("data/measurements") else []
    log:
        notebook="logs/specimen_measurements_done.log" #log file path
    output:
        touch("data/measurements/.done")

rule concatenate_measurements: #Rule to concatenate the measurements from all the images into a single csv file.
    input:
        "data/measurements/.done" #input folder path of the measurements generated by the measure_fish rule    
    log:
        notebook="logs/concatenate_measurements.log" #log file path
    output:
        "data/measurements/specimen_scales.csv" #csv file containing the concatenated measurements of all the images in the raw_images folder.
    shell:
        "python3 scripts/Extract_Scales.py"

