configfile: "resources/configs/StickleSnake.yaml" #We need to specify the config file that contains the parameters for the script

rule all:
    input:
        "data/cropped_images" #This is the final output of the pipeline, which is the folder containing the labelled images after processing.


rule read_label: #Rule to read the label using a trained OCR model and save the output 
    input:
        images_dir="data/raw_images" #input folder path
    output:
        "data/raw_images/label_log.json" #log file (robust in case files are renamed, as the log file will be saved in the same directory as the images)
    container:
        config["container"] #We need to specify the container that contains the trained OCR model and the necessary dependencies to run the script
    log:
        notebook="logs/read_label.log" #log file path
    shell:
        "python3 scripts/read_label.py "
        "--log_file {config[log_file_label]} "
        "--image_dir {input.images_dir} "
        "--flip {config[flip_label]} "
        "--pattern {config[pattern]} "
        "--rename {config[rename]} "
        "--save_ocr_visualization {config[save_ocr_visualization]}"

rule crop_fish: #Rule to read a fish image, crop the fish using the bounding box coordinates obtained from the OCR model and save the cropped image in a new folder. This step is optional and can be skipped if the user only wants to read the labels without cropping the images. 
    input:
        "data/raw_images/label_log.json", #log file generated by the read_label script, meaning that this has run to completion and the labels have been read successfully.
        images_dir="data/raw_images" #input folder path
    output:
        directory("data/cropped_images") #folder of cropped images created by the script (robust in case files are renamed, as the cropped images will be saved in a new folder)
    container:
        config["container"] #We need to specify the container that contains the trained model and the necessary dependencies to run the script
    log:
        notebook="logs/crop_fish.log" #log file path
    shell:
        "python3 scripts/crop_images.py "
        "--path {input.images_dir} "
        "--flip {config[right_side_up]} "
        "--out_dir {output} "
        "--pipeline_config_path {config[crop_config]} "
        "--label_path {config[crop_label_file]} "
        "--checkpoint {config[checkpoint_prefix]} "
        "--save_bbox_coordinates {config[save_bbox_coordinates]} "
        "--display_image_with_bbox {config[display_image_with_bbox]} "
        "--save_image_with_bbox {config[save_image_with_bbox]} "
        "--save_cropped_image {config[save_cropped_image]}"
