log_file: /mnt/data/label_log.json
flip: false
pattern: "[A-Z]{2}[0-9]{2}[A-Z][0-9]{3}"
rename: true
save_ocr_visualization: false
visualization_dir: "/mnt/data/debug"
container: "/storage/homefs/rs23l510/containers/crop_fish.sif"
