import phenopype as pp
import json, cv2, os
import argparse

def main(input_image, input_template, input_annotation):

    ref_template = cv2.imread(input_template)
    with open(input_annotation) as f:
        template_data = json.load(f)

    image = pp.load_image(input_image)
    # AKAZE matching runs headlessly against the saved template
    annotation = pp.preprocessing.detect_reference(
        image,
        template      = ref_template,
        px_ratio = template_data["reference"]["a"]["data"]["reference"][0],
        unit = template_data["reference"]["a"]["data"]["reference"][1],
    )

    image_stem = input_image.split("/")[-1].split(".")[0]
    template_stem = input_template.split("/")[-1].split(".")[0]
    os.makedirs("data/measurements", exist_ok=True)
    pp.core.export.save_annotation(annotation, dir_path="data/measurements/", file_name=f"{image_stem}_{template_stem}_annotation.json") 

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Measure fish using template matching.")
    parser.add_argument("--input_image", type=str, required=True, help="Path to the uncropped image that we want to measure.")
    parser.add_argument("--input_template", type=str, required=True, help="Path to the template image generated by the initialize_templates_light.py script. This template image will be used for the template matching step to find the location of the template in the input image.")
    parser.add_argument("--input_annotation", type=str, required=True, help="Path to the annotation file generated by the initialize_templates_light.py script, which contains the pixel/unit distance data for the template image.")
    args = parser.parse_args()

    main(args.input_image, args.input_template, args.input_annotation)